### ISSUE TITLE
Add MQ support to POSIX bindings

### ISSUE THREAD

**Issue by magthe** [jwiegley/bindings-dsl#13]
Is there a specific reason for omitting bindings to the POSIX message queue API?

**Comment by jwiegley** [comment]
Not that I'm aware of.

**Comment by magthe** [comment]
Then I'd love to see bindings for it :)

**Comment by jwiegley** [comment]
Pull requests welcome? :)

**Comment by magthe** [comment]
I'm looking at `mqueue.h` now and notice that there are two versions of `mq_open`, one taking 2 arguments and one taking 4.  The definition is `mqd_t mq_open(const char *name, int oflag, ...)`, but there are only two allowed variants: `mqd_t mq_open(const char *name, int oflag)` and `mqd_t mq_open(const char *name, int oflag, mode_t mode, struct mq_attr *attr)`.

So, now the question is how to handle this.  I'm guessing I'll need two functions, but then what to call them?  Is there some similar situation in bindings that I can use as guidance?

**Comment by jwiegley** [comment]
Is this a C++ overloaded function, or are these two C functions guarded by a preprocessor variable?

**Comment by magthe** [comment]
No, this is a Posix API, so ordinary C, and also no preprocessor guards, rather it's defined as a variadic function but it only accepts 2 or 4 arguments.

You can find the details at <http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/mqueue.h.html> and <http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_open.html>.

After a little thought I expect I'll have to write two C wrapper functions... unless there's a variant of `#ccall` that allows me to specify the C function name separate from the Haskell name (hopefully that isn't too unclearly stated).

**Comment by magthe** [comment]
I have a first attempt using two minimal wrappers, `mq_open_2` and `mq_open_4`.  What do you think of that?

**Comment by jwiegley** [comment]
Let me know if this merge can close this issue, and I'll release a new `bindings-DSL`.

**Comment by magthe** [comment]
Yupp, the merge can close this issue.
