### ISSUE TITLE
Feature request: pattern synonyms for numeric constants

### ISSUE THREAD

**Issue by RyanGlScott** [jwiegley/bindings-dsl#22]
Currently, `bindings-DSL` has a `#num` form that turns this:

```c
#num IM_A_NUMBER
```

into this:

```haskell
c'IM_A_NUMBER = 42
c'IM_A_NUMBER :: (Num a) => a
```

Unfortunately, it's rather awkward to use these in bidirectional pattern synonyms. You'd have to concoct something like:

```haskell
pattern I'mANumber <- ((== c'IM_A_NUMBER) -> True) where
    I'mANumber = c'IM_A_NUMBER
```

So why not enrich `bindings-DSL` with the ability to create these pattern synonyms directly? Then you could type:

```c
#pattern IM_A_NUMBER
```

and directly get:

```haskell
pattern c'IM_A_NUMBER = 42
pattern c'IM_A_NUMBER :: () => (Eq a, Num a) => a
```

Similarly to [how the `gl` library does it](http://hackage.haskell.org/package/gl-0.7.8/docs/Graphics-GL-Ext-EXT-GeometryShader4.html#v:GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT).

Operationally, `#pattern` behaves almost exactly as `#num` would, so implementing it wouldn't be too challenging. There are some design questions that I'd like your input on, though:

1. This requires `-XPatternSynonyms` to be on. Should `bindings-DSL` enable this extension automatically, or should we require users to enable it themselves?
2. Also, `-XPatternSynonyms` has only been around since GHC 7.8. What happens if a user tries using `#pattern` on an unsupported GHC version? Should `bindings-DSL` give an `#error`? Or should it default to the `#num` behavior (perhaps with a warning)?

**Comment by jwiegley** [comment]
That sounds like a nice feature; and we could use CPP to #ifdef guard in the case of older versions of GHC.

**Comment by RyanGlScott** [comment]
I didn't realize until after this was merged that this doesn't allow for fractional patterns like `pattern Foo = 1.23`. #24 fixes that.
