### ISSUE TITLE
Proposal: Make bindings-dsl more robust w.r.t. variadic functions

### ISSUE THREAD

**Issue by RyanGlScott** [jwiegley/bindings-dsl#25]
Currently, the syntax of `bindings-dsl` restricts you to having one Haskell function per C function. This limitation is especially annoying when dealing with variadic functions. For example, in C you have:

``` c
int ioctl(int d, unsigned long request, ...);
```

In Haskell, you can make multiple `foreign import`s of `ioctl` with different type signatures quite easily, but `bindings-dsl` doesn't currently give you a way to leverage this:

``` c
#ccall ioctl  , CInt -> CULong -> Ptr () -> IO CInt
#ccall ioctl2 , CInt -> CULong -> Ptr () -> Ptr () -> IO CInt // Doesn't work, unfortunately
```

What if we had variants of the `#ccall` and `#callconv` macros that allowed you to bind the Haskell function names to something other than the C function names? I propose introducing `#ccall_var` and `#callconv_var` which lets you type:

``` c
#ccall_var ioctl , ioctl1 , CInt -> CULong -> Ptr () -> IO CInt
#ccall_var ioctl , ioctl2 , CInt -> CULong -> Ptr () -> Ptr () -> IO CInt
```

Which will generate the following:

``` haskell
foreign import ccall "ioctl" c'ioctl1
  :: CInt -> CULong -> Ptr () -> IO CInt
foreign import ccall "ioctl" p'ioctl1
  :: FunPtr (CInt -> CULong -> Ptr () -> IO CInt)

foreign import ccall "ioctl" c'ioctl2
  :: CInt -> CULong -> Ptr () -> Ptr () -> IO CInt
foreign import ccall "ioctl" p'ioctl2
  :: FunPtr (CInt -> CULong -> Ptr () -> Ptr () -> IO CInt)
```

(Better naming suggestions are welcome.)

**Comment by RyanGlScott** [comment]
#26 implements this.

**Comment by RyanGlScott** [comment]
Closing stale issue.

**Comment by jwiegley** [comment]
Thanks for the house-keeping, @RyanGlScott!
