### ISSUE TITLE
[bindings-gpgme] versions mixup

### ISSUE THREAD

**Issue by dmalikov** [jwiegley/bindings-dsl#30]
On [hackage](https://hackage.haskell.org/package/bindings-gpgme) there are `0.1.4` and `0.1.6`.
At the same time, in latest HEAD it's `0.1.5`.

https://github.com/jwiegley/bindings-dsl/blob/ec36a594f98f6255ea145ea67f96013981107f7f/bindings-gpgme/bindings-gpgme.cabal#L13

Shouldn't these be in sync?

**Comment by jwiegley** [comment]
You're right, they certainly should be. I think it's been forever since these packages were last uploaded; would you like to fix this and upload?

**Comment by jwiegley** [comment]
What's your username on Hackage?

**Comment by dmalikov** [comment]
DmitryMalikov

**Comment by dmalikov** [comment]
@jwiegley `bindings-gpgme` is the package :)

**Comment by jwiegley** [comment]
You're added there too. :)

**Comment by dmalikov** [comment]
Uploaded. Thank you
